In [1]:
import dash
import dash_core_components as dcc
import dash_html_components as html
import pandas as pd

C:\Users\iitak\miniconda3\envs\amit_python\lib\site-packages\ipykernel_launcher.py:2: UserWarning:
The dash_core_components package is deprecated. Please replace
`import dash_core_components as dcc` with `from dash import dcc`

C:\Users\iitak\miniconda3\envs\amit_python\lib\site-packages\ipykernel_launcher.py:3: UserWarning:
The dash_html_components package is deprecated. Please replace
`import dash_html_components as html` with `from dash import html`
  This is separate from the ipykernel package so we can avoid doing imports until

In [2]:
data = pd.read_csv("Yearwise data.csv")



app = dash.Dash(__name__)

In [3]:
data

,Year,Government Canals,Tanks,Wells,Tubewells,Other sources,Total,Percentage\nto net area sown,Area by tubewells
0,1967,991,4,289,0,9,"1,293",37.8,0.000000
1,1971,952,1,574,0,5,"1,532",43.0,0.000000
2,1981,"1,161",0,26,941,6,"2,134",59.2,0.440956
3,1991,"1,337",1,0,"1,248",14,"2,600",72.7,0.480000
4,2001,"1,476",1,0,"1,467",14,"2,958",83.9,0.495943
5,2006,"1,331",0,0,"1,591",14,"2,936",82.3,0.541894
6,2011,"1,236",0,0,"1,650",1,"2,887",82.1,0.571528
7,2016,"1,162",0,0,"1,850",2,"3,014",85.6,0.613802
8,2017,"1,181",0,0,"1,996",0,"3,177",90.8,0.628266
9,2018,"1,208",0,0,"2,053",0,"3,261",93.0,0.629561
10,2019,"1,215",0,0,"2,067",0,"3,282",91.1,0.629799

In [4]:
app.layout = html.Div(
    children=[
        html.H1(children="Area Irrigated",),
        html.P(
            children=" Analysing Year wise area irrigated by various techniques",
        ),
        dcc.Graph(
            figure={
                "data": [
                    {
                        "x": data["Year"],
                        "y": data["Area by tubewells"],
                        "type": "lines",
                    },
                ],
                "layout": {"title": "Area by tubewells"},
            },
        ),
        dcc.Graph(
            figure={
                "data": [
                    {
                        "x": data["Year"],
                        "y": data["Total"],
                        "type": "lines",
                    },
                ],
                "layout": {"title": "net area sown year wise "},
            },
        ),
    ]
)

In [ ]:
app.run_server(port = 8090, dev_tools_ui=True, #debug=True,
              dev_tools_hot_reload =True, threaded=True)

Dash is running on http://127.0.0.1:8090/

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

 * Running on http://127.0.0.1:8090/ (Press CTRL+C to quit)
127.0.0.1 - - [21/Apr/2022 14:29:32] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2022 14:29:33] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2022 14:29:33] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2022 14:29:34] "GET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2022 14:29:34] "GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2022 14:29:36] "GET /_reload-hash HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2022 14:29:39] "GET /_reload-hash HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2022 14:29:42] "GET /_reload-hash HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2022 14:29:45] "GET /_reload-hash HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2022 14:29:48] "GET /_reload-hash HTTP/1.1" 200 -
127.0.0.1 - - [21/Apr/2022 14:29:51] "GET /_reload-hash HTTP/1.1" 200 -